stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python .\src\data\data_preprocessing.py
    deps:
    - .\src\data\data_preprocessing.py
    - data/raw
    outs:
    - data/processed
  model_building:
    cmd: python .\src\model\model_building.py
    deps:
    - .\src\model\model_building.py
    - data/processed
    params:
    - model_building.n_estimators
    outs:
    - model.pkl
  model_evaluation:
    cmd: python .\src\model\model_evaluation.py
    deps:
    - .\model.pkl
    - .\src\model\model_evaluation.py
    metrics:
    - metrics.json
